version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    allow:
      - dependency-type: direct
    cooldown:
      default-days: 3
    open-pull-requests-limit: 25
    schedule:
      interval: daily
    groups:
      test:
        patterns:
          - "climate_control"
          - "database_cleaner-*"
          - "factory_bot*"
          - "pact*"
          - "rspec-*"
          - "simplecov"
          - "webmock"
      mongo: 
        patterns:
          - "mongo*"
          - "*-mongoid"

  # Ruby needs to be upgraded manually in multiple places, so cannot
  # be upgraded by Dependabot. That effectively makes the below
  # config redundant, as ruby is the only updatable thing in the
  # Dockerfile, although this may change in the future. We hope this
  # config will save a dev from trying to upgrade ruby via Dependabot.
  - package-ecosystem: docker
    directory: /
    cooldown:
      default-days: 7
    open-pull-requests-limit: 25
    schedule:
      interval: weekly
    ignore:
      - dependency-name: ruby
  - package-ecosystem: github-actions
    directory: /
    cooldown:
      default-days: 3
    open-pull-requests-limit: 25
    schedule:
      interval: daily
