source 'https://rubygems.org'

gem 'addressable'
gem 'aws-sdk', '~> 2.0'
gem 'carrierwave', '~> 0.11.2'
gem 'carrierwave-mongoid', '~> 0.10.0', require: 'carrierwave/mongoid'
gem 'gds-sso', '~> 14.0'
gem 'govuk_app_config', '~> 1.12'
gem 'govuk_sidekiq', '~> 3.0'
gem 'jwt', '~> 2.1'
gem 'mongoid', '~> 6.2.0'
gem 'nokogiri', '~> 1.10.1'
gem 'plek', '~> 2.1'
gem 'rack_strip_client_ip', '0.0.2'
gem 'rails', '5.2.2.1'
gem 'rails-controller-testing'
gem 'state_machines-mongoid', '~> 0.2.0'
gem 'unicorn', '5.4.1'

group :development, :test do
  gem 'byebug'
  gem 'climate_control'
  gem 'database_cleaner'
  gem 'factory_bot_rails'
  gem 'govuk-lint'
  gem 'rspec-rails'
  gem 'simplecov-rcov'
end
