name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths-ignore:
      - "Jenkinsfile"
      - ".git**"
  pull_request:

jobs:
  cache-dependencies:
    name: Cache dependencies
    uses: alphagov/govuk-infrastructure/.github/workflows/cache-dependencies.yaml@main

  security-analysis:
    name: Security Analysis
    needs: cache-dependencies
    uses: alphagov/govuk-infrastructure/.github/workflows/brakeman.yaml@main

  lint-ruby:
    name: Lint Ruby
    needs: cache-dependencies
    uses: alphagov/govuk-infrastructure/.github/workflows/rubocop.yaml@main

  test-ruby:
    name: Test Ruby
    needs: cache-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Setup MongoDB
        uses: alphagov/govuk-infrastructure/.github/actions/setup-mongodb@main

      - name: Setup Redis
        uses: alphagov/govuk-infrastructure/.github/actions/setup-redis@main

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Initialize database
        env:
          RAILS_ENV: test
        run: bundle exec rails db:setup

      - name: Run Rspec
        env:
          RAILS_ENV: test
        run: bundle exec rake spec

